# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 18:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='close',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='open',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='volume',
        ),
    ]
