# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0003_stock_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
    ]
