# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0005_auto_20170915_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='name',
        ),
    ]
