# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0007_stock_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stock_app.Stock'),
        ),
    ]
