# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-20 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0008_auto_20170920_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
